[profile.default]
src = "src"
out = "out"
libs = ["base"]
ignored_warnings = ["Source not found", "File import callback failed"]

remappings = [
    "@openzeppelin/contracts=base/openzeppelin-contracts/contracts",
    "@forge-std=base/forge-std/src"
]

[rpc_endpoints]
anvilFork = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
